"""Typed boundaries used by hosted research application services."""

from __future__ import annotations

from collections.abc import Callable
from typing import Literal, Protocol

from portfell.entitlements import ProviderDownloadRun
from portfell.hosted_api_state import AnalysisRecord, ProjectRecord, SelectionRecord
from portfell.hosted_research_workflow import FilterSelection, ResearchRun
from portfell.table_io import JsonRow

ResearchDataset = Literal["quotes", "dividends"]
UnivariateProgress = Callable[[int], None]


class ResearchDataPort(Protocol):
    """Read and derive project-scoped market data without exposing storage details."""

    def selected_rows(
        self, member_ids: tuple[str, ...], *, dataset: ResearchDataset
    ) -> tuple[JsonRow, ...]: ...

    def build_univariate_rows(
        self,
        member_ids: tuple[str, ...],
        *,
        on_progress: UnivariateProgress | None = None,
    ) -> tuple[JsonRow, ...]: ...


class ResearchPersistencePort(Protocol):
    """Persist the current research workspace after a durable transition."""

    def persist(self) -> None: ...


class ResearchRunRepository(Protocol):
    """Store and retrieve user-scoped research records."""

    def metadata_selection(self, selection_id: str, user_id: str) -> SelectionRecord: ...

    def quote_run(self, run_id: str, user_id: str) -> ProviderDownloadRun: ...

    def quote_rows(self, run_id: str) -> tuple[JsonRow, ...]: ...

    def univariate_run(self, run_id: str, user_id: str) -> ResearchRun: ...

    def find_univariate_run(self, run_id: str) -> ResearchRun | None: ...

    def save_univariate_run(self, run: ResearchRun) -> None: ...

    def delete_univariate_run(self, run_id: str) -> None: ...

    def bind_quote_run(self, univariate_run_id: str, quote_run_id: str) -> None: ...

    def quote_run_id(self, univariate_run_id: str) -> str: ...

    def filter_selection(self, selection_id: str, user_id: str) -> FilterSelection: ...

    def filter_selections(self, user_id: str) -> tuple[FilterSelection, ...]: ...

    def save_filter_selection(self, selection: FilterSelection) -> FilterSelection: ...

    def set_current_filter_selection(self, user_id: str, selection_id: str) -> None: ...

    def bivariate_run(self, run_id: str, user_id: str) -> ResearchRun: ...

    def find_bivariate_run(self, run_id: str) -> ResearchRun | None: ...

    def save_bivariate_run(self, run: ResearchRun) -> None: ...

    def project(self, project_id: str, user_id: str) -> ProjectRecord: ...

    def analysis(self, run_id: str, user_id: str) -> AnalysisRecord: ...

    def save_analysis(self, analysis: AnalysisRecord) -> None: ...

    def cached_id(self, user_id: str, operation: str, key: str | None) -> str | None: ...

    def remember_id(self, user_id: str, operation: str, key: str | None, row_id: str) -> None: ...

    def audit(self, user_id: str, action: str) -> None: ...
